#postgress


spring.application.name=TAB-Lab1_excercise
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/flowers-postgres
spring.datasource.username=bar
spring.datasource.password=foo
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

#mysql

# Adres URL do MySQL (localhost, port 3306, nazwa bazy z Dockerfile)
#spring.datasource.url=jdbc:mysql://localhost:3306/flowers-mysql?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=bar
#spring.datasource.password=foo
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
# Dialekt Hibernate (wa?ne, ?eby Spring wiedzia?, ?e ma "mówi?" w j?zyku MySQL)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
# Opcjonalne: pokazuje zapytania SQL w konsoli IntelliJ (pomaga przy debugowaniu)
#spring.jpa.show-sql=true


#H2

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl.auto=update
#spring.jpa.defer-datasource-initialization=true
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.show-sql=true
#logging.level.org.hibernate.orm.jdbc.bind=trace